version: '3'

services:
  app:
    image: golang:1.9.4-alpine
    volumes:
      - .:/go/src/go-config/app
    working_dir: /go/src/go-config/app
    command: go run main.go
    links:
      - redis
    environment:
      REDIS_URL: redis:6379
      APP_PORT: 5000
    ports:
      - 5000:5000
    
  redis:
    image: "redis:alpine"